<?php
$title = 'Excluir Produto';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>
	Você realmente quer deletar o produto
    '<?php echo $this->escapeHtml($produto->produto_nome); ?>' ?
</p>

<form action="" method="post">
	<div>
	    <input type="hidden" name="id" value="<?php echo (int) $produto->produto_id; ?>" />
	    <input type="submit" name="del" value="Sim" />
	    <input type="submit" name="voltar" value="Voltar" />
	</div>
</form>